# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/terraformbuch"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Ressourcen"
  wigth = 30

[[main]]
  name = "Online-Anhang"
  pre = "github"
  parent = "Ressourcen"
  url = "https://github.com/terraformbuch/anhang"
  weight = 10

[[main]]
  name = "Beispiele"
  pre = "github"
  parent = "Ressourcen"
  url = "https://github.com/terraformbuch/beispiele"
  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Autoren"
  pageRef = "authors"
  weight = 20

[[footer]]
  name = "Impressum"
  pageRef = "imprint"
  weight = 30

[[footer]]
  name = "Datenschutz"
  pageRef = "dataprotection"
  weight = 40
